name: Generate RSS & Sitemap

on:
  push:
    branches: [main, master]
    paths:
      - '**/*.html'
      - 'tools/generate_rss.py'
      - 'tools/generate_sitemap.py'
      - '.github/workflows/rss.yml'
  schedule:
    - cron: '17 5 * * *'   # ежедневно 05:17 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # нужно для git log (даты файлов)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate rss.xml
        env:
          BASE_URL: https://dostup-plus.github.io
          SITE_TITLE: SAFENET-VPN — Руководства и инструкции по VPN
          SITE_DESCRIPTION: Гайды по VPN, обходу блокировок и скачиванию видео (YouTube/VK/TG/TikTok, MP3).
          MAX_ITEMS: '0'
        run: |
          python tools/generate_rss.py
          echo "RSS head:"
          head -n 20 rss.xml || true

      - name: Generate sitemap.xml
        env:
          BASE_URL: https://dostup-plus.github.io
          MAX_URLS: '49000'
          MAKE_ROBOTS: '1'
        run: |
          python tools/generate_sitemap.py
          echo "Sitemap head:"
          head -n 20 sitemap.xml || true

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Стадим только реально существующие файлы
          for f in rss.xml sitemap.xml sitemap_index.xml robots.txt; do
            if [ -f "$f" ]; then git add "$f"; fi
          done

          # Если нечего коммитить — выходим
          if git diff --cached --quiet; then
            echo "No changes in rss/sitemap"
            exit 0
          fi

          git commit -m "chore: auto-generate rss.xml & sitemap.xml [bot]"
          git push
